package hu.mpb.backendchess64.model;

public enum ChessResult {
    ONGOING,
    WIN_WHITE_RESIGNATION,
    WIN_WHITE_MATE,
    WIN_WHITE_ABANDONMENT,
    WIN_BLACK_RESIGNATION,
    WIN_BLACK_MATE,
    WIN_BLACK_ABANDONMENT,
    DRAW_STALEMATE,
    DRAW_3_TIME_REPETITION,
    DRAW_INSUFFICIENT_MATERIAL,
    DRAW_50_MOVE_RULE,
    DRAW_AGREEMENT
}
